### ISSUE TITLE
pyorient not compatible with OrientDB 2.1.2

### ISSUE THREAD

**Issue by d1g1t4l** [mogui/pyorient#109]
OrientDB 2.1.2 uses the binary protocol version 32. pyorient fails if the version is greater than 30. My understanding is that version 32 is backwards compatible with version 30. Redefining SUPPORTED_PROTOCOL to 32 worked with my tests so far (creating classes, properties and vertices, running a batch and doing simple queries).

**Comment by hanneslehmann** [comment]
Confirmed, same error on my side. Any workaround until the update?

**Comment by jwogrady** [comment]
confirmed still the case.
