### ISSUE TITLE
OGM doesn't appear to support multiple inheritance

### ISSUE THREAD

**Issue by lebedov** [mogui/pyorient#113]
Although OrientDB 2.1+ [supports multiple inheritance of db classes](http://orientdb.com/orientdb-2-1-rc1/), it appears that the OGM in pyorient (as of 44f6815) can't currently create a class with multiple parents; when run against OrientDB 2.1.2 with the aforementioned revision of pyorient installed, the following code fails at `g.create_all(Foo.registry)` because it tries to create the OrientDB `baz` before `foo` or `bar` are created.

```
from pyorient.ogm import Graph, Config
from pyorient.ogm.declarative import declarative_node, declarative_relationship
from pyorient.ogm.property import String
import pyorient.ogm.property

class Foo(declarative_node()):
    element_type = 'foo'
    element_plural = 'foos'
    name = String(nullable=False, unique=False)

class Bar(declarative_node()):
    element_type = 'bar'
    element_plural = 'bars'
    name = String(nullable=False, unique=False)

class Baz(Foo, Bar):
    element_type = 'baz'
    element_plural = 'bazs'
    name = String(nullable=False, unique=False)

if __name__ == '__main__':
   g = Graph(Config('localhost', 2424, 'admin', 'admin', 'ogm', initial_drop=True)) 

   g.create_all(Foo.registry)
   g.create_all(Bar.registry)
   g.create_all(Baz.registry)
```

Copying @TropicalPenguin

**Comment by TropicalPenguin** [comment]
I'll take a closer look at this later, but at a glance, try creating a
single (grand-)parent:

Node = declarative_node()

class Foo(Node):

class Bar(Node):

class Baz(Foo,Bar):

Then you should only need to do:

g.create_all(Node.registry)

Each declarative_*() call will create a registry, shared by all inheriting
from it.

**Comment by lebedov** [comment]
@TropicalPenguin: confirmed that your suggestion works.
