### ISSUE TITLE
Orientdb returning empty strings.

### ISSUE THREAD

**Issue by jwogrady** [mogui/pyorient#118]
Can't get a valid response.....

Using Python 3.5.0 connecting to orientdb-2.1.3.

I've verified the port is open.  Tried the following test code

    import pyorient
    db_name = "GratefulDeadConcerts"
    client = pyorient.OrientDB("10.0.0.26", 2480)
    client.set_session_token(True)
    cluster_info = client.db_open( db_name, "admin", "admin" )

following error w/ stack trace

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwogrady/projects/huckster/venv/lib/python3.5/site-packages/pyorient/orient.py", line 234, in db_open
    return self.get_message("DbOpenMessage") \
  File "/Users/jwogrady/projects/huckster/venv/lib/python3.5/site-packages/pyorient/orient.py", line 355, in get_message
    return _Message(self._connection)\
  File "/Users/jwogrady/projects/huckster/venv/lib/python3.5/site-packages/pyorient/messages/database.py", line 48, in __init__
    super( DbOpenMessage, self ).__init__(_orient_socket)
  File "/Users/jwogrady/projects/huckster/venv/lib/python3.5/site-packages/pyorient/messages/base.py", line 40, in __init__
    sock.get_connection()
  File "/Users/jwogrady/projects/huckster/venv/lib/python3.5/site-packages/pyorient/orient.py", line 41, in get_connection
    self.connect()
  File "/Users/jwogrady/projects/huckster/venv/lib/python3.5/site-packages/pyorient/orient.py", line 57, in connect
    "Server sent empty string", []
pyorient.exceptions.PyOrientConnectionPoolException: Server sent empty string
````

**Comment by jwogrady** [comment]
The error I got is probably because I'm using the HTTP port.  When I use port 2424 I get the "Protocol version 32 is not supported yet by this client" error which is a known issue.

**Comment by Ostico** [comment]
Hi @jwogrady 

i just tried and it worked fine with orientdb-2.1.3. 

Be sure to update Pyorient to the last version.

**Comment by jwogrady** [comment]
@Ostico I am/was using Using python 3.5.0 connecting to orientdb-2.1.3.  What version on Python were you using for test?

**Comment by anux-linux** [comment]
@jwogrady Did you solved the issue? Because I´m stuck with the same problem using python 2.7.9 orientDB 2.1.3 and 2.1.4 and pyorient version 1.4.4

**Comment by Ostico** [comment]
@jwogrady pyorient works with python 2.7.x and with python 3.x, more specifically, tests are run with 2.7 , 2.7.6, 3.4. I will try to add some tests for python 3.5

**Comment by anux-linux** [comment]
@Ostico I'v did some debug and found some strange things:
when installing via ```pip install pyorient``` the installed version is 1.4.4
```
C:\Users\me\git\PWS\orientDBTest>pip show --version pyorient
    ---
    Metadata-Version: 1.0
    Name: pyorient
    Version: 1.4.4
    Summary: OrientDB native client library
    Home-page: UNKNOWN
    Author: Niko Usai <mogui83@gmail.com>, Domenico Lupinetti <ostico@gmail.com>
    Author-email: UNKNOWN
    License: LICENSE
    Location: c:\python27\lib\site-packages
    Requires:
C:\Users\me\git\PWS\orientDBTest>pip install --upgrade pyorient
    Requirement already up-to-date: pyorient in c:\python27\lib\site-packages

```
But in the the code in ```constants.py``` running at runntime you see this:
```python
#
# Driver Constants
#
NAME = "OrientDB Python binary client (pyorient)"
VERSION = "1.4.3"
SUPPORTED_PROTOCOL = 30
```
This is what causes the exception.

**Comment by ramtinms** [comment]
I had the same problem, after 3 hours of debugging, I found what was the wrong for me: port number!!!! , If you use http port (e.g. 2480) instead of binary port (e.g. 2424) you will get the same error : "Server sent empty string".

**Comment by Ostico** [comment]
@mogui , we must check the pip package creation automation. 
Seems not working well, or at least it seems not wotking everytime.

This is the actual version on Github
```python
NAME = "OrientDB Python binary client (pyorient)"
VERSION = "1.4.6"
SUPPORTED_PROTOCOL = 32
```
But on Pipy the last version is pyorient 1.4.5c :
https://pypi.python.org/pypi?%3Aaction=search&term=pyorient&submit=search

**Comment by pawarchinmay27** [comment]
@ramtinms I tried your solution instead it gave me an error Protocol version 37 is not supported yet by this client

**Comment by Siddhesh177** [comment]
@pawarchinmay27 , did you figure out how to connect?

**Comment by sow-ibrahima** [comment]
Got the same problem with pyorient 1.5.5 on python 3.7.4. Hope someone could help me please.
