### ISSUE TITLE
Import schema from the database

### ISSUE THREAD

**Issue by lodrion** [mogui/pyorient#120]
It would be useful to import the OGM schema for selected classes/inheritance subtrees from the DB instead of having to define them in code

**Comment by TropicalPenguin** [comment]
@lodrion: Almost done. 

A method on Graph with the signature 'build_mapping(self, vertex, edge, class_names=None)'

Where vertex and edge will be, for example, types returned by declarative_node() and declarative_relationship(), respectively, and class_names can be a list of class names.

This will return a registry suitable for passing to Graph.include(). It seems this functionality will also make it useful to add a tool to automatically generate python code based on registries.

A current limitation is that, if names are supplied, they must - at least, to work when g.registry is uninitialised - include all intermediate nodes in an inheritance hierarchy between V/E and your desired subclass(es).

Getting rid of this limitation doesn't seem worth the effort, but its presence also makes me question how useful this parameter is at all. Could a compromise be to just simplify the signature, and allow users to build mappings for vertexes OR edges (not necessarily both) by selectively providing those arguments instead?

**Comment by TropicalPenguin** [comment]
Ahem, not all intermediate nodes. If V/E aren't specified, then their immediate children between them and the desired subclasses must be.

**Comment by lodrion** [comment]
I think importing schema whole-sale from the graph is a good intermediate solution. The advantage being that users can then interrogate the schema in python. I threw this together (which kinda works)

https://gist.github.com/lodrion/a558da3ec535e39e347f

**Comment by TropicalPenguin** [comment]
@lodrion Here's my attempt.

I don't know how to query indexes, so those property attributes are currently lost. This also preserves class hierarchies, so no need to merge properties manually.

Here's the slightly ugly code to support sub-tree selection. Since the whole schema is queried anyway,    it shouldn't hurt too much to let users just interrogate the returned classes on their own, as you suggest.

```python
included = not class_names or class_name in class_names
if not included:
    for base in bases:
        for name in class_names:
            if name == 'V' and issubclass(base, vertex):
                included = True
                break
            elif name == 'E' and issubclass(base, edge):
                included = True
                break
            else:
                named_class = registry.get(name, type(None))
                if not named_class:
                    named_class = self.registry.get(name, type(None))
                if issubclass(base, named_class):
                    included = True
                    break
        else:
            continue
        break

if bases and included:
```

**Comment by lodrion** [comment]
Here are the indexes
>> select expand(indexes) from #0:2
aka g.client.record_load("#0:2").oRecordData
