### ISSUE TITLE
OGM transactions

### ISSUE THREAD

**Issue by lodrion** [mogui/pyorient#121]
It looks like it is impossible to combine transactions with OGM-style updates, since the command results are local to the graph modification functions e.g. https://github.com/mogui/pyorient/blob/master/pyorient/ogm/graph.py#L265

could be useful to add transaction capabilities to the graph as well

**Comment by Ostico** [comment]
Hi @lodrion,
The ogm are basically built on top of sql commands. 

So, You're right, it is not possible to combine ogm feature with transactions because they are not provided by OrientDB binary protocol for sql commands.

You can ask to OrientDB team about that.

**Comment by lodrion** [comment]
I believe it could be done using the new batch command http://orientdb.com/new-sql-command-batch/
but it would require somewhat significant modifications.

The problem I am trying to solve is atomic creation of subgraphs (each individual node or edge is somewhat meaningless

**Comment by Ostico** [comment]
The Batch command is already implemented by PyOrient. It is a different use of sql command, so the command itself can not be used in transaction because they only works for CRUD methods, but the SQL batch can be used to exec pipelined sql operations.

**Comment by lodrion** [comment]
Right, the problem is that there is no way of wrapping OGM-based graph changes into a single batch for execution. I am hand-waving here, but it could work like this:

graph.start_batch()  # this starts assembling the batch
graph.person.create(name = "blah")   # Instead of running create_vertex this would add a statement to the batch and return the batch variable id 
# let a = create vertex person name="blah"
graph.commit_batch() # this flushes the assembled batch making ogm operations effectively a transaction

**Comment by TropicalPenguin** [comment]
@lodrion Like Query, it would be cool to isolate this out.

Perhaps:

batch = graph.transaction()
batch['a'] = batch.person.create(name='blah')
batch.commit()
a = batch['a']

I won't be able to get to this for a few weeks.

**Comment by TropicalPenguin** [comment]
Curiosity got the better of me; most of this is pretty straightforward to get working. Should be able to get something committed within a week.

**Comment by TropicalPenguin** [comment]
Hi @lodrion, hopefully this meets your needs.

**Comment by lodrion** [comment]
@TropicalPenguin looks great, thanks!
