### ISSUE TITLE
Querying edges

### ISSUE THREAD

**Issue by lodrion** [mogui/pyorient#127]
I can't figure out how to query for an (ogm) edge between two known vertices? Is it possible to do with query().filter() ?

**Comment by TropicalPenguin** [comment]
@lodrion filter() corresponds to the WHERE clause of the SELECT. You'll need to use what(), which - along with property specifications - takes those things defined in what.py (for this purpose, inE(), outE(), bothE())

Those functions, along with outV(), inV(), out(), in_(), both(), can be chained - e.g. query.outE().inV().outE('<edge-label>'))

**Comment by mogui** [comment]
@TropicalPenguin should we close this?

**Comment by fredmajor** [comment]
How do I query edge properties using this syntax?
