### ISSUE TITLE
Management for non-graph/embedded types

### ISSUE THREAD

**Issue by lodrion** [mogui/pyorient#133]
It would be useful to have schema management for non-graph types in orient db. 

A usecase I am contemplating is having a class with an embedded map from string to objects of a particular class. Having a representation for the value class automatically imported (and being able to create in-memory instances of that would be very useful

**Comment by mogui** [comment]
you mean define a schema for a class and automatically have that class as results of queries instead of the generic record?

**Comment by lodrion** [comment]
Not quite. 
the latest addition let us build OGM schema from the database. But that includes models only for classes that derive from vertices and edges. I was trying to experiment with embedded maps from string to an object, where an object is not itself derived from a vertex. And the current class import skips those. 

But it looks like orientdb itself does not quite support those https://github.com/orientechnologies/orientdb/issues/3511
