### ISSUE TITLE
Protocol version 32 is not supported yet by this client

### ISSUE THREAD

**Issue by zero-** [mogui/pyorient#143]
*posted this already at https://github.com/orientechnologies/pyorient/issues/9 but it seems this repo is more active*

Getting `Protocol version 32 is not supported yet by this client` and I'm running 2.1.5.

Any ETA support for newer protocols?

**Comment by Ostico** [comment]
Hi @zero- ,

OrientDB protocol 32 is already supported by pyorient: 
https://github.com/mogui/pyorient/blob/master/pyorient/constants.py#L8

What is you pyorient version?

**Comment by zero-** [comment]
Hey @Ostico, just installed it from pip yesterday and the version is 1.4.4.

**Comment by Ostico** [comment]
Check this, 

https://pypi.python.org/pypi/pyorient

There coud be some issues with last pyp push, let me know.

**Comment by zero-** [comment]
`pip install pyorient` install 1.4.4 because using `pip install -v -v -v pyorient` told me that all newer releases are consider "pre-releases" so I had to use `pip install --pre --upgrade pyorient` to upgrade to `1.4.6a`.

**Comment by Ostico** [comment]
Pip lies!! :)

Consider them stable, i will fix as soon as possible.

**Comment by pkoppstein** [comment]
@ostico (and anyone else interested): It's January 2016, and "pip install pyorient" still installs 1.4.4.  Meanwhile, thanks for the tip about "pip install --pre --upgrade ..."

**Comment by ycaxgjd** [comment]
`pip install --pre --upgrade pyorient`
thank you very much!
