### ISSUE TITLE
Unicode strings with codepoints at or below \u00ff are encoded as \x?? rather than \u00??

### ISSUE THREAD

**Issue by obi1kenobi** [mogui/pyorient#146]
This is a different facet of the unicode encoding issue mentioned in #129, which is unfortunately not solved by PR #142. This is because of two issues:
- Python chooses to represent \u00?? codepoints as \x??, which is not supported by OrientDB.
- on Python 2, pyorient uses `str` values internally, which are implicitly encoded with `ascii` and therefore cannot correctly represent all of Unicode.

To reproduce, add a unicode value that contains the `\u00c5` character (latin capital letter a with ring above, AKA Angstrom unit symbol normalized) and attempt to write it to OrientDB.

**Comment by Ostico** [comment]
Can i close?

**Comment by obi1kenobi** [comment]
Ah yes I think this was fixed. Closing.
