### ISSUE TITLE
Query ignore limit parameter, part 2

### ISSUE THREAD

**Issue by obi1kenobi** [mogui/pyorient#153]
#45 is only partially fixed by https://github.com/mogui/pyorient/commit/0d551fce8e363771510613194dc74e61724c956d

```
In [5]: len(client.query('SELECT * FROM MyTable limit 100'))
Out[5]: 21

In [6]: len(client.query('SELECT * FROM MyTable LIMIT 100'))
Out[6]: 20
```

I was unfortunately unable to reopen the issue, so I have to open a new one.

Additionally, do you think it would be possible to remove the implicit 'LIMIT 20' added to queries? It's not mentioned anywhere in the documentation and is unintuitive -- if I pass a SQL command, I expect it executed as-is *unless* I specify a limit parameter.

**Comment by Ostico** [comment]
Hi @obi1kenobi ,

OrientDB team suggests to do not remove the limit, so i propose this fix, let me know your doubt or suggestions.

https://github.com/mogui/pyorient/pull/183

**Comment by obi1kenobi** [comment]
#184 looks like it would work, but it would be best to have some tests to be sure that it stays working :) :+1:

**Comment by Ostico** [comment]
Of course
Il 11 apr 2016 3:45 PM, "Predrag Gruevski" <notifications@github.com> ha
scritto:
