### ISSUE TITLE
Implement auto-reconnect on server restart

### ISSUE THREAD

**Issue by amitlicht** [mogui/pyorient#154]
After a restart of the orientdb server, the pyorient client can no longer communicate with it. 
Right now our only resolution in this case is to restart our entire server (which uses pyorient as it's orientdb client) each time the orientdb server has to be restart. That much for availability. 

Suggestion: when identifying connection problems, try to reconnect at least once. Only if the reconnection fails, raise a connection error. The price may be one lost message, which is way better then restarting the entire server (at least in our case). 

Would love to hear your opinion.

**Comment by amitlicht** [comment]
update: eventually we decided to catch connectivity problems which appear on command executions (socket.error & PyOrientConnectionException) and create a whole new pyorient client context. This is not optimal, but works. In my opinion supporting it directly in the pyorient library would be better.

**Comment by mogui** [comment]
yep should be handled by your code by catching the exception
