### ISSUE TITLE
Problem with serialization of a list of strings.

### ISSUE THREAD

**Issue by neRok-** [mogui/pyorient#165]
There is a problem with the code in `OrientSerializationCSV._encode_value()`, as it throws an error when attempting to join a list of string values. Below is the current code.
PS- I haven't bothered to learn how to use github yet, so my code pasting here will have to do.

    elif isinstance(value, list):
        try:
            ret = "[" + ','.join(
                map(
                    lambda elem: self._parse_value(type(value[0])(elem))
                    if not isinstance(value[0], OrientRecordLink)
                    else elem.get_hash(),
                    value
                )) + ']'
        except ValueError as e:
            raise Exception("wrong type commistion")
    elif isinstance(value, dict):
        ret = "{" + ','.join(map(
            lambda elem: '"' + elem + '":' + self._parse_value(value[elem]),
            value)) + '}'

The `self._parse_value()` method calls need changing to `_encode_value`. This is definitely required for a list (in my tests), and I presume the same will hold true for dict.

Further to this, the lambda seems a bit dodgy to me, as it is referencing it's own variables, plus the local variables of the _encode_value method (ie self and value are the local variables of _encode_value function, not the lambda function). I believe the following code makes it clearer. Perhaps it should be changed?

    elif isinstance(value, list):
        try:
            base_cls = type(value[0])
        except IndexError:
            elements = value
        else:
            if issubclass(base_cls, OrientRecordLink):
                elements = [elem.get_hash() for elem in value]
            else:
                try:
                    elements = [
                        self._encode_value(base_cls(elem))
                        for elem in value
                    ]
                except ValueError as e:
                    raise Exception("wrong type commistion")
        ret = "[" + ",".join(elements) + "]"

**Comment by Ostico** [comment]
Hi @neRok- 
don't worry for git.
Anyway i will try to apply your patch but without git you will lose your signature on this fix.

More important, can you send me your test code? In this manner i can reproduce and fix the error.
Later i will insert such code it in the test suite to avoid future regressions.

**Comment by erikwiffin** [comment]
I'm not sure if this is the same bug or not, but I've run into some issues creating records with embedded lists and dictionaries. I can load records with them:

```python
client.record_load('9:2')
# {'@V':{'foo':` ['bar']},'version':2,'rid':'9:2'}
client.record_load('9:3')
# {'@V':{'foo': [{'bar': 'bar'}]},'version':4,'rid':'9:3'}
```

but if I attempt to create my own I get an exception:

```python
rec = {'@V': {'foo': [{'bar': 'bar'}]}}
pos = client.record_create(9, rec)
# AttributeError: 'dict' object has no attribute 'lstrip'
```

I don't have a fix, but I do have two failing tests https://github.com/erikwiffin/pyorient/commit/80521357579c8fb7e6464e3fe906e23c41bf4f31.

**Comment by Ostico** [comment]
Fixed, tnx @neRok- for the contribution.
