### ISSUE TITLE
how to connect orientdb cluster

### ISSUE THREAD

**Issue by gaoxuesong** [mogui/pyorient#177]
My orientdb cluster has two host in one server, the hosts ports are 2425 and 2426.
How to connect the orientdb cluster?

**Comment by lebedov** [comment]
I assume you meant that two separate OrientDB installations are running on the same host. If so, specify the port of the server you want to connect to as follows:

```
import pyorient
client = pyorient.OrientDB('myhostname', 2425)
client.connect('name', 'password')
...
```

**Comment by Ostico** [comment]
Tnx @lebedov .

I close
