### ISSUE TITLE
string of query result is not unicode

### ISSUE THREAD

**Issue by rainkin1993** [mogui/pyorient#178]
python:2.7.8
pyorient:1.4.7

the result from query command is not unicode string

I have the same problems in this question http://stackoverflow.com/questions/26749081/python-unicodedecodeerror-on-long-query-using-pyorient, which @Ostico answered.

What's more, I run the test code in pyorient/tests/test_utf8_string.py.
Take the test_utf8_words for example,

`
>self.client.command( "insert into my_v_class ( 'model') values ('kfjgkfgòàòT:導字社; S:导字社')" )
>res = self.client.command("select from my_v_class")
>print repr(res[0].model) == repr(u'kfjgkfgòàòT:導字社; S:导字社')
>False
>print repr(res[0].mode)
>'kfjgkfg\xc3\xb2\xc3\xa0\xc3\xb2T:\xe5\xb0\x8e\xe5\xad\x97\xe7\xa4\xbe;S:\xe5\xaf\xbc\xe5\xad\x97\xe7\xa4\xbe'  

`

**Comment by mogui** [comment]
We had some issues publishing to pip, so as said in SO by @Ostico you should have an old version, try installing now the new ;) or reopen if still buggy
