### ISSUE TITLE
why database returns only 20 values

### ISSUE THREAD

**Issue by el3ctron** [mogui/pyorient#180]
i just doing a query in a database that have 58 registers but when i connect and do
```

query1 = "select * from "+vertice
for i in client.query(query1):
    print i

```
it returns only 20!  ??

Using Studio version : 2.1
OrientDB version : 2.1.14

and last version of pyorient

**Comment by TropicalPenguin** [comment]
You're right, this needs to be fixed :) When I initially implemented it,
not providing a limit caused the query to hang, but I'm sure there must be
a better approach.

**Comment by el3ctron** [comment]
ok i find a solution changing 

`for i in client.query(query1):`

by 

`
for i in client.**command**(query1):`

**Comment by pabloa** [comment]
Try: 

`client.query(query1, 200)  # 200 = LIMIT 200`

**Comment by Ostico** [comment]
Hi @el3ctron , i know it should be better explained, but refer to this:
https://github.com/mogui/pyorient#make-a-query

The first number is the limit in the query, te latter one is the fetchPlan and you can refer to this:
http://orientdb.com/docs/2.1/Fetching-Strategies.html#format-for-fetch-plans
