### ISSUE TITLE
Support for OrientDB 2.2.x

### ISSUE THREAD

**Issue by kaYcee** [mogui/pyorient#185]
First of all: great driver! Are there any plans to support also OrientDB 2.2.x (ie binary protocol version 33 and above) or will this require a (potentially) new driver?

**Comment by Ostico** [comment]
Yes, the support is obviously in plan. 
When OrientDB 2.2.x will be released as suitable for production environments the support will be tested and the driver upgraded to support this version.

**Comment by fauskanger** [comment]
I get the PyOrientWrongProtocolVersionException when trying to connect to OrientDB 2.2.0 using pyorient 1.4.9.

> PyOrientWrongProtocolVersionException: Protocol version 36 is not supported yet by this client.

Am I correct in that support for 2.2.x is going to resolve this?

**Comment by karel-un** [comment]
+1

**Comment by Ostico** [comment]
Upgrading. The protocol changed significantly and some issues on documentation slowed work. Will be updated as soon as possible. I apologize for the delay.

**Comment by pabloa** [comment]
+1

**Comment by kaYcee** [comment]
Hi @Ostico, thx for the update. Unfortunately line 235 in otypes.py still seems to cause some issues due to its integer conversion. Since the 2.2.0 Community Edition identifies itself as `OrientDB Server v2.2.0 (build develop@r79d281140b01c0bc3b566a46a64f1573cb359783; 2016-05-18 14:14:32+0000) is starting up.` it appears that the naming causes some trouble... as a workaround I commented the affected line but cannot assess whether this has any repercussions.

**Comment by Ostico** [comment]
Tnx @kaYcee.
No ripercussion on that for 99% of functionalities . Tnx for the string, i will improve the check.

**Comment by fauskanger** [comment]
Thanks for the update! Excited!
