### ISSUE TITLE
Calling db_exists after calling db_open closes the database

### ISSUE THREAD

**Issue by lovesh** [mogui/pyorient#186]
After i open a database using `db_open`, i can create classes and do other operations and things are fine. But if i call `db_exists` on an already opened database and then try to some operation it results in the error `pyorient.exceptions.PyOrientDatabaseException: com.orientechnologies.orient.core.exception.ODatabaseException - Database 'memory:<db name>' is closed`

Here is the code to reproduce it

```python
# Creating the database
import pyorient
client = pyorient.OrientDB("localhost", 2424)
dbName = "test"
user = "root"
password = "password"
session_id = client.connect(user, password)
client.db_create(dbName, pyorient.DB_TYPE_GRAPH, pyorient.STORAGE_TYPE_MEMORY)
client.db_open(dbName, user, password)
client.command("create class Car")   # this works
client.db_exists(dbName, pyorient.STORAGE_TYPE_MEMORY)
client.command("create class Bike")   # this fails
```
I get this exception
```
>>> client.command("create class Animal")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lovesh/.virtualenvs/penv/lib/python3.5/site-packages/pyorient/orient.py", line 411, in command
    .prepare(( QUERY_CMD, ) + args).send().fetch_response()
  File "/home/lovesh/.virtualenvs/penv/lib/python3.5/site-packages/pyorient/messages/commands.py", line 145, in fetch_response
    super( CommandMessage, self ).fetch_response()
  File "/home/lovesh/.virtualenvs/penv/lib/python3.5/site-packages/pyorient/messages/base.py", line 256, in fetch_response
    self._decode_all()
  File "/home/lovesh/.virtualenvs/penv/lib/python3.5/site-packages/pyorient/messages/base.py", line 240, in _decode_all
    self._decode_header()
  File "/home/lovesh/.virtualenvs/penv/lib/python3.5/site-packages/pyorient/messages/base.py", line 192, in _decode_header
    [ exception_message.decode( 'utf8' ) ]
pyorient.exceptions.PyOrientDatabaseException: com.orientechnologies.orient.core.exception.ODatabaseException - Database 'memory:test' is closed
```

But if i call `db_open` again it works so 
```python
client.db_exists(dbName, pyorient.STORAGE_TYPE_MEMORY)
client.db_open(dbName, user, password)
client.command("create class Bike")   # Now this works
```

**Comment by mogui** [comment]
Hi @lovesh,
This is not an issue it's how orientdb works. 
You should not mix **server** commands with **database**, beside the fact that I do not understand why you need it, and that by chance your server and databse share the same user passwords, which should not be the case, here's what happens
- you connect as *root* with `connect`
- then create a db 
- next you open the db with `db_open` that it's a way to connect to the server as *user*
- now you have a database opened
- you issue a `db_exists` a **server** command and that command **closes the opened database**

in my opinion it's strange that even the `db_exists` works, anyway you're using it wrong :D
