### ISSUE TITLE
Float truncation

### ISSUE THREAD

**Issue by nosepy** [mogui/pyorient#188]
When storing a Python float value as part of a record to OrientDB and reading it from the DB again, the precision is truncated. It seems that the Python float is mapped to a Java float with the first one corresponding actually to a C double precision. Therefore I would assume that the Python float should be mapped to a Java double instead of Java float.
When I change one line in function _encode_value in serializations.py from
ret = str(value) + 'f' to ret = str(value) + 'd' the problem is gone. 
Could you please confirm this.

I am using pyorient 1.4.9.

**Comment by TropicalPenguin** [comment]
Fixed in https://github.com/mogui/pyorient/commit/3ab37aabe2b7041c119d97231eef73b31ebb391c.
