### ISSUE TITLE
very slow SELECT when vertex include quite populated embedded set

### ISSUE THREAD

**Issue by karel-un** [mogui/pyorient#191]
Week ago I have posted issue on OrientDB:

[https://github.com/orientechnologies/orientdb/issues/6101](https://github.com/orientechnologies/orientdb/issues/6101)

But it looks like there is some performance problem when decoding large embedded set in pyorient.

So I repost it here and will close on OrientDB.

**Comment by mogui** [comment]
will look into that

**Comment by mogui** [comment]
Hi @karel-un 
> Yes, both pyorient and the console use the binary protocol, so the problem is not there. The only difference here is on the driver, so I suspect the problem is there

This it's not true we're still using the old CSV serialization. I could verify the performance issue,
We're deciding whether to try and **optimize the current** or to **implement the binary protocol** (pure python or using the c binding)

anyway it will be not very soon, sorry :D

**Comment by karel-un** [comment]
Should I reopen issue on OrientDB to have them look at CSV, or do you think problem is in parsing in pyorient ?

We have overcomed this by excluding embedded set from result as seen in original issue, so it is not important for us anymore. I just think it should be sorted in some way. I guess that binary protocol is faster, so if you decide to implement it, it will probably bring not only fix to this, but overall performance gains.

**Comment by nikulukani** [comment]
I have started working on implementing the binary protocol (#204). Results in considerable speedup (~10x-50x in my case) when retrieving records with heavily populated maps/lists.

**Comment by karel-un** [comment]
Native binary serialization protocol is here:
https://pypkg.com/pypi/pyorient-native/
Sorry for being late to close issue.
