### ISSUE TITLE
Update selected properties of a vertex in a class

### ISSUE THREAD

**Issue by dhirender-tyagi** [mogui/pyorient#192]
I am not able to update selected properties of a vertex in a class.
i.e I have a object of properties of a vertex like {"name":"toni", "age":"28"} now I want update "name" property to "dhirender" and add one new properties "lastName" with value "tyagi" and age should be remain same. So with using 
record_update("cluster_id", "r_id", {"@classname":"abc", {"name":"dhirender", "lastName":"tyagi"}}, r_version)

It is working fine but this will replace {"name":"toni", "age":"28"} to {"name":"dhirender", "lastName":"tyagi"}. It removes "age" property from the record.

Please let me know how can I update a record as I want.

**Comment by Ostico** [comment]
Actually, the protocol and the driver, does not support the partial update in the CRUD methods.
You must use SQL commands.

**Comment by dhirender-tyagi** [comment]
Thnx @Ostico
