### ISSUE TITLE
client.db_open errors

### ISSUE THREAD

**Issue by JannisT69** [mogui/pyorient#196]
hi,

i always get an error with db_open, my sample code

Python v3.5.1 / 64bit
OrientDB Server v2.2.0

```
import pyorient
client = pyorient.OrientDB("192.168.1.2", 2424)
conn_id = client.connect( "root", "12345pass" )
dataBase = "DD_NAMES"

# db_create & db_drop works fine
#client.db_create( dataBase, type='graph', storage='plocal' )
#client.db_drop(dataBase)

client.db_open( dataBase, "root", "12345pass" )
```

Error:

Traceback (most recent call last):
  File "R:/PyCharm_Projects/orientDB.py", line 8, in <module>
    client.db_open( dataBase, "root", "12345pass" )
  File "C:\Python35\lib\site-packages\pyorient\orient.py", line 379, in db_open
    .prepare((db_name, user, password, db_type, client_id)).send().fetch_response()
  File "C:\Python35\lib\site-packages\pyorient\messages\database.py", line 141, in fetch_response
    info = OrientVersion(release)
  File "C:\Python35\lib\site-packages\pyorient\otypes.py", line 202, in __init__
    self._parse_version(release)
  File "C:\Python35\lib\site-packages\pyorient\otypes.py", line 235, in _parse_version
    self.build = int( self.build )
ValueError: invalid literal for int() with base 10: '0 (build develop@r79d281140b01c0bc3b566a46a64f1573cb359783; 2016'

**Comment by Ostico** [comment]
Hi @JannisT69 , already fixed in the last release. Please upgrade your version. Re-open the issue if it is not closed or properly fixed.

**Comment by JannisT69** [comment]
Seems to still be a problem. I installed pyorient-1.5.2 with pip and still got the same issue

**Comment by Ostico** [comment]
I think that some issues with Pip occurred. The driver is at version 1.5.3b

https://github.com/mogui/pyorient/blob/master/setup.py#L22

**Comment by Ostico** [comment]
@mogui , please can you send me a mail with pip-deploy configuration details, alternatively can you check what went wrong?

Tnx :grin:

**Comment by mogui** [comment]
@Ostico everything should be automated with trevis, I mean the pushing to pip.
By a quick check seems pypi is down for maintenance https://pypi.python.org/ and serving a freezed mirror could be that?

**Comment by Ostico** [comment]
@mogui don't know, but seems that the last package on Pip is 1.5.2

**Comment by mogui** [comment]
will check

**Comment by meatballs** [comment]
I have this problem too - pip installed v1.5.2

**Comment by mogui** [comment]
should be fixed now https://pypi.python.org/pypi/pyorient/
