### ISSUE TITLE
client.command() returns wrong cluster_ids on create class

### ISSUE THREAD

**Issue by imainetti** [mogui/pyorient#201]
_orientdb 2.2.3
pyorient 1.5.4
Python 2.7.11_

```
cluster_id_1 = client.command("create class test1 extends v")
print("Cluster: "+`cluster_id_1`+"\n")
```
output:
`Cluster: [11]`

but looking via console the class test1 is associated with other clusters:
```
orientdb {db=testDB}> info class test1

CLASS 'test1'

Records..............: 0
Super classes........: [V]
Default cluster......: test1 (id=17)
Supported clusters...: test1(17), test1_1(18), test1_2(19), test1_3(20)
Cluster selection....: round-robin
Oversize.............: 0.0
```

am I doing something wrong or is this actually a bug?
Thanks

**Comment by Ostico** [comment]
This is known issue. Please refer to this link: https://github.com/orientechnologies/orientdb/issues/6258

**Comment by imainetti** [comment]
Ok thanks!
