### ISSUE TITLE
OrientRecord - JSON Serialisation Issue

### ISSUE THREAD

**Issue by kfloz** [mogui/pyorient#217]
Hi,

I am trying to execute this query using pyorient:

response = client.query("select @this.toJson('rid,version,fetchPlan:in_*:-2 out_*:-2') from Worker where userName = '" + userName + "'")

Im expecting 0 or 1 result, but the SQL itself returns JSON and can confirm it works in studio.  When used as part of a microservice, I get the error below as the OrientRecord:

<pyorient.otypes.OrientRecord object at 0x7feb13272990> is not JSON serializable"

As the select statement returns JSON from the server, how can I use pyorient query for this?

Cheers
Kurt

**Comment by anber500** [comment]
I tried running your query in my version of pyorient and the result came back fine. How are you trying to parse the json?

The json should be in a variable called "this".
Try making that call like this:

    res = client.command("SELECT @this.toJson('rid,version,fetchPlan:in_:-2 out_:-2') FROM Worker WHERE userName = '%s';" % userName)
    obj = json.loads(res[0].this)

**Comment by mogui** [comment]
@kfloz yep should work as @anber500 work
