### ISSUE TITLE
WAL mode changed to false, causes fail on batch commit

### ISSUE THREAD

**Issue by sps90** [mogui/pyorient#220]
v2.2.4
java version 1.8.0_101
[x ] Windows

I am working on defining schema for loading data in batches from pyorient ogm.
As per performance tuning documentation, i have changed the value of storage.useWAL=false in tag in orientdb-server-config.xml, but the following error occurs 
"pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.
exception.OStorageException - WAL mode is not active. Transactions are not supported in given mode"

![image](https://cloud.githubusercontent.com/assets/11362115/19086244/2caa1a2a-8a22-11e6-883c-c4a41bd1afad.png)

**Comment by mogui** [comment]
this i ssomething dealing with the orient configuration, the error is an exception raised by the OrientDB server
