### ISSUE TITLE
Set Default for DateTime as current timestamp

### ISSUE THREAD

**Issue by decebal** [mogui/pyorient#228]
I am not sure this is a fault or just my limited understanding of it.

Here is an example of an edge definition:
```
class VerifiedBy(Edge):
    label = 'verified_by'
    date = property.DateTime(nullable=False, default=now())

def now():
    return datetime.now(timezone.utc).astimezone()
```

they all seemed to work right, but the function `now` is evaluated just once, when the types are seeded to orient DB and the default remains set as that. Are there any ways to solve this within the ogm ?

I was looking for something similar to [bulbs'](https://github.com/espeed/bulbs) `current_timestamp`.

**Comment by decebal** [comment]
Similar to the Uuid property I have tweaked my function to look like this:

```
def now():
    return 'sysdate()'
```

but it has the disadvantage of not being able to set a timezone. If that's a solution I would like to add it to the library in a pull-request as well.

**Comment by TropicalPenguin** [comment]
Hi decebal,

Sorry for the late reply. No need for a pull request, it's already there, and you can pass a time-zone.

`from pyorient.ogm.what import sysdate`

which is defined:

```
def sysdate(fmt=None, tz=None):
     return FunctionWhat(What.SysDate, (fmt, tz))
```

**Comment by decebal** [comment]
thanks @TropicalPenguin , I was wondering about that `what` module, looks promising , but I am not sure how to begin understanding how I can use it.
