### ISSUE TITLE
broker `query` is working anymore for attribute base filtering

### ISSUE THREAD

**Issue by decebal** [mogui/pyorient#241]
Something like this, where memories would be the broker does not work anymore ... 
`self.graph().memories.query(uuid=memory.get('uuid')).one()`

TypeError: query() got an unexpected keyword argument 'uuid'

is this likely to be fixed or would the switch to query_command make sense in the future ?

**Comment by TropicalPenguin** [comment]
The _command functions are only used by batches to generate SQL strings... I should probably add comments that they're not meant to be used directly. That, and, if query isn't working, query_command should not work either.

That said, it seems downright bizarre how this would be failing but the test case OGMDateTimeTestCase would be succeeding. I also have code which depends on this, so...

Can you copy here the signature of query() (inside your copy of pyorient/ogm/broker.py) and also, the output of:

`print(self.graph().memories)`

**Comment by decebal** [comment]
Hmm, interesting, just reverted my dependency to development branch and the query on Broker has double stars again, when I submitted this it didn't use to.
