### ISSUE TITLE
Select Link fields in OGM queries

### ISSUE THREAD

**Issue by golfarelli** [mogui/pyorient#245]
Refered to: orientechnologies/pyorient#26
@TropicalPenguin 

Hi, I'm still learning the driver and testing ogm queries before starting to use it in my application.
I've created some Node classes and now I would select some properties through Link field.

This is my code
```python
SchemaNode = declarative.declarative_node()
SchemaRelationship = declarative.declarative_relationship()


class Role(SchemaNode):
    element_plural = 'roles'
    element_type = 'Role'
    name = String()


class User(SchemaNode):
    element_plural = 'users'
    element_type = 'User'
    first_name = String()
    last_name = String()
    email = String()
    role = Link(linked_to=Role)
    active = Boolean()


graph = Graph(Config.from_url('DB', 'root', 'pwd', initial_drop=False))
graph.include(SchemaNode.registry)

query = graph.users.query().what(User.first_name, User.role.name).filter_by(first_name='Fabio')
for u in query:
    print(u)

graph.client.db_close()
```
But the result is
```python
User_props(first_name='Fabio', None_=None)
```

How can I select the link fields ?
Is there any documentation on ogm queries ?

Thanks in advance

**Comment by TropicalPenguin** [comment]
Hi @golfarelli, it looks like you've got the right idea. On queries themselves, unfortunately the docs are pretty sparse.

Sorry your first encounter ran into that problem with Link properties. this latest commit should fix a number of limitations I came across while investigating your findings. That query should now work. Your code also drew my attention to graph lacking a more direct means of closing the DB connection; have added one.

Most of the interfaces on Query map fairly clearly to the OrientDB select clause, so its documentation will give most of the background. More OGM-specific things to get used to are:
- LET variables. Subsequently accessible via `QV` instances passed to the what clause (of the current query or queries for which the current query is a subquery).
- Queries (or as of recently, traversals) within queries, a.k.a. subqueries. The .sub() method is a useful way to gradually build up layers of these. unionall() also, when combined with QV, makes some pretty neat things possible.
- The things you can pass to `Query.what()`, from vertex and edge properties, to the variables, functions, and method calls defined in pyorient.ogm.what.

**Comment by golfarelli** [comment]
Great! Now the query works correctly!
Thanks @TropicalPenguin  for the fix
