### ISSUE TITLE
ogm broker hangs on creating vertexes in a distributed environment

### ISSUE THREAD

**Issue by decebal** [mogui/pyorient#250]
Unfortunately, I don't really know where to look for more information on this, running on my local environment hangs after the create command is executed.

`
Request :
00000000: 29 00 00 00 08 73 00 00  00 8D 00 00 00 31 63 6F  )....s.......1co
00000010: 6D 2E 6F 72 69 65 6E 74  65 63 68 6E 6F 6C 6F 67  m.orientechnolog
00000020: 69 65 73 2E 6F 72 69 65  6E 74 2E 63 6F 72 65 2E  ies.orient.core.
00000030: 73 71 6C 2E 4F 43 6F 6D  6D 61 6E 64 53 51 4C 00  sql.OCommandSQL.
00000040: 00 00 50 43 52 45 41 54  45 20 56 45 52 54 45 58  ..PCREATE VERTEX
00000050: 20 63 6F 6D 6D 65 6E 74  20 53 45 54 20 74 65 78   comment SET tex
00000060: 74 3D 22 54 78 74 22 2C  75 75 69 64 3D 22 65 62  t="Txt",uuid="eb
00000070: 32 66 64 66 34 62 2D 64  62 32 39 2D 34 39 37 31  2fdf4b-db29-4971
00000080: 2D 39 33 65 38 2D 32 35  31 63 32 38 39 32 66 35  -93e8-251c2892f5
00000090: 63 34 22 00 00 00 00                              c4"....
`

Versions:
pyorient==1.5.5
pyorient_native==1.1.1
orientdb community edition 2.2.22

This does not happen for all of my vertexes, some of them can be created, but I can't single out a reason for this type, although it looks like there are at least a couple other vertex classes that have the same problem.

Note: this does not happen when running without the distributed flag.

**Comment by TropicalPenguin** [comment]
Especially having never run distributed before, I'm at a loss for how to help without some guidance on how to reproduce this.

**Comment by decebal** [comment]
Short update, realised the other vertex "create" commands are ran through a `batch`, I'll try that for myself.

@TropicalPenguin easiest thing to have orientdb running in distributed mode is to have dserver.sh as your entrypoint ($ORIENTDB_HOME/bin next to server.sh) or just add the "-Ddistributed=true" added to `server.sh` execution.

You can run just one server in distributed mode, it's not valuable for the data, but it creates a similar dev environment for pyorient which behaves a little bit differently, unfortunately :(

**Comment by decebal** [comment]
```
from pyorient.ogm.declarative import declarative_node
from pyorient.ogm import Graph, Config, property
import pyorient

Node = declarative_node()
class Name(Node):
    element_type = 'name'
    element_plural = 'names'
    verified = property.Boolean()

graph = Graph(Config.from_url('hardware', 'root', 'root', serialization_type=pyorient.OrientSerialization.Binary))
graph.clear_registry()
graph.include(Node.registry)

name = {
    'uuid': 'random-invalid-uuid',
    'verified': True
}

# while this works
batch = graph.batch()
batch['name1'] = batch.names.create(
    verified=name.get('verified', False),
    uuid=name.get('uuid')
)
comment_vertex = batch['$name1']

# this hangs
new_vertex = graph.names.create(
    verified=name.get('verified', False),
    uuid=name.get('uuid')
)
```

**Comment by TropicalPenguin** [comment]
@decebal After making that ugly little tweak to REQUEST_PUSH_DISTRIB_CONFIG payload handling, and upgrading to 2.2.23, I had more luck. Perhaps that will help you too.

I suspect both issues share a related cause.

**Comment by TropicalPenguin** [comment]
Hi @decebal, can this and #251 be closed?

**Comment by decebal** [comment]
hi @TropicalPenguin , I was on holiday until today, plan to test this today or tomorrow at most .. 

do you not feel that this should stay open for a long term solution though ?

**Comment by TropicalPenguin** [comment]
I'd be surprised if made further improvements any more likely than the comments in https://github.com/mogui/pyorient/commit/b1cda333df92e47ce7a3a094ee141c42e5b87f3b, but I guess it can't hurt.

**Comment by decebal** [comment]
hi @TropicalPenguin , just tried in production, unfortunately there are no positive changes, still running an infinite loop.

**Comment by decebal** [comment]
Alright, So I managed to reproduce the bug in it's entirety and solved it on the server side for my setup.

Extra Step needed to replicate:
 - run a distributed config with `"writeQuorum": "majority"`

On orientdb 2.2.15 this would fail only on updates with "ODatabaseExceptionQuorum" exception which is not caught by the broker.

**Comment by decebal** [comment]
Closing this as #251 should be the same.
