### ISSUE TITLE
ODistributedRecordLockedException or ONeedRetryException not dealt with

### ISSUE THREAD

**Issue by decebal** [mogui/pyorient#258]
Hi guys,

I am running a distributed cluster with 2 nodes on orientdb: 2.2.29 , but I am met with the exception mentioned in the title: `ODistributedRecordLockedException`

The guys at orientdb propose it's dealt with something like this:
https://github.com/orientechnologies/orientdb/issues/5012#issuecomment-312335527

Is there any ongoing investigation to do with this issue on implementation ?

Regards

**Comment by Ostico** [comment]
HI @decebal ,
the first thing to do is to instruct the method you called that the server is running as distributed environment.

Please provide more info on what you done

**Comment by decebal** [comment]
I can see it's already re-trying, that was the only problem I thought I am reporting, but it's already doing it. Must be a configuration issue then.
