### ISSUE TITLE
Performance PyOrient x Console

### ISSUE THREAD

**Issue by marcoaleixo** [mogui/pyorient#271]
Hello, 
 when I run directly on ./console.sh a query, this one actually is taking 

> "87599 item(s) found. Query executed in 0.426 sec(s)."

And when I run using pyorient with that config:

```
db_name = "dbdbdb"
client = pyorient.OrientDB("192.168.1.175", 2424)
client.db_open(db_name, "root", "root")


start = time.time()
my_select = client.command("SELECT test FROM Test")
done = time.time()
elapsed = done - start
```

the exactly same query takes almost 4.60731482506 seconds.
Am I  missing something?
Thank you.

**Comment by Ostico** [comment]
Hi @marcoaleixo ,

console.sh is a bash wrapper of the OrientDB Java client, by definition pyorient is slowest. I think it is normal.

**Comment by marcoaleixo** [comment]
Hi @Ostico
And do you know any way to increase that, like using another way to connect to Orientdb using python?

**Comment by Ostico** [comment]
You can try with pyorient_native as decoder. and binary serialization.

**Comment by marcoaleixo** [comment]
Thank you @Ostico , I think this isn't a issue anymore.
Do you think is a good ideia post the benchmark here or does not matter actually!?
Thank you for the support!

**Comment by Ostico** [comment]
Why not, every contribution is well accepted.
