### ISSUE TITLE
Connection timeout/interruption detection

### ISSUE THREAD

**Issue by DeividasJackus** [mogui/pyorient#33]
The driver performs no checks for timeouts or server restart which results in blocking calls to the socket's recv() method.

If a timeout occurs or the server is restarted while a pyorient instance is active, it is possible to cause a KeyboardInterrupt (when using a CLI) or set additional checks/timeouts outside the module before calling the driver's methods.

An argument could be made that this is an enhancement that has to be implemented before the driver can actually be used in a production environment, especially when deployed with WSGI instances.

**Comment by lodrion** [comment]
Hi.

This fix is for the read side of the communication. But the problem still exists on the write side -- when the connection has been stale for a while, the orientdb server drops it, and any new command needs to write first.. And the thread completely blocks on write. 

So the same change needs to be applied to https://github.com/mogui/pyorient/blob/master/pyorient/orient.py#L94 

Additionally it would be nice if the dropped connections resulted in PyOrientConnectionException and not re-raising select.error
