### ISSUE TITLE
Doc enhancement

### ISSUE THREAD

**Issue by mjmare** [mogui/pyorient#39]
I'd appreciate some info in the docs on how to connect in a web app (say Flask).
Can the Client be global? Should the connection be opened for each request? Should the connection be closed (how?)

TIA

**Comment by Ostico** [comment]
PyOrient is a lightweight binary client easy to add to other softwares/libraries.

Feel free to try to add to Flask and send me every bug/bad behaviour you find so i can improve it.
Follow documentation provided on how to use PyOrient.

    Should the connection be opened for each request? Should the connection be closed (how?)

You need create a connection for every request, but in the next release i will implement the OrientDB session token. 

Session token is a new OrientDB functionality that provide persistent per-user connections.

You can close opened connections with the ```client.db_close()``` command once a database is opened, or destroy the opened socket with ```client._connection.close()``` if no database was opened
with ```client.db_open()```command.
