### ISSUE TITLE
Driver not handling @rid projection

### ISSUE THREAD

**Issue by sinfex** [mogui/pyorient#41]
The driver seems to mishandle the projection of @rid during a query. Since the following is a projection, oRecordData['rid'] should be set to '#11:0'. Instead the RID is stored as the generated document's RID and not part of the projection. Also, if I'm not mistaken, record.rid should be equal to #-1:-1 in this case, since projections result in temporary documents.

```
>>> record = DB.query("SELECT @rid, @class FROM #11:0")[0]
>>> record.oRecordData
{'class': 'Article'}                     <--- missing `rid' projection
>>> record.rid
<pyorient.types.OrientRecordLink object at 0x7fbad1fc4a20>
>>> str(record.rid)
'#11:0'                                  <--- there it is; shouldn't this be #-1:-1 instead?
```

Console and Studio produce the following results, properly projecting the record meta data to strings:

```
orientdb {db=testdb}> SELECT @rid, @class FROM V
----+------+-----+-------
#   |@CLASS|rid  |class
----+------+-----+-------
0   |null  |#11:0|Class1
1   |null  |#12:0|Class2
2   |null  |#13:0|Class3
```

*Temporary workaround*

Currently, in cases when I need to retrieve and re-use a RID and want to access it through oRecordData, I have to project it under a different name:

```
>>> DB.query("SELECT @rid as oid FROM #11:0")[0].oRecordData['oid']
<pyorient.types.OrientRecordLink object at 0x7fbad1fc4b00>
```

I'm personally not very fond of OrientRecordLink, especially because I often end up encoding record data into JSON strings. This results in me having to force OrientDB to convert it to a string first:

```
>>> DB.query("SELECT @rid.asString() as oid FROM #11:0")[0].oRecordData['oid']
'#11:0'
```

Alternatively, its string representation seems to work fine for now.

```
>>> str(DB.query("SELECT @rid as oid FROM #11:0")[0].oRecordData['oid'])
'#11:0'
```

**Comment by Ostico** [comment]
Hi sinfex,
this is by design, to avoid interference with reserved words.
https://github.com/mogui/pyorient/blob/master/pyorient/types.py#L27

Example of possible mistakes if value is projected:
https://github.com/mogui/pyorient/blob/master/test/test_reserved_words_batch.py#L78

This is what the console does ( and in my opinion this is a bad behaviour ):
```
orientdb {db=test_tr}> insert into V ( 'rid', 'version', 'model', 'ciao') values ('test_rid', 'V1', '1123', 1234)
orientdb {db=test_tr}> select rid, @rid, model, ciao from V
----+------+--------+----+-----+----
#   |@CLASS|rid     |rid2|model|ciao
----+------+--------+----+-----+----
0   |null  |test_rid|#9:0|1123 |1234
----+------+--------+----+-----+----

orientdb {db=test_tr}> select @rid, rid, model, ciao from V 
----+------+----+--------+-----+----
#   |@CLASS|rid |rid2    |model|ciao
----+------+----+--------+-----+----
0   |null  |#9:0|test_rid|1123 |1234
----+------+----+--------+-----+----
```

You can obtain the rid as string caling get() method from OrientRecord.rid:
```python
DB.query("SELECT @rid as oid FROM #11:0")[0].rid.get()
```

**Comment by sinfex** [comment]
I am aware of that scenario and have found [this thread](https://groups.google.com/d/msg/orient-database/uiP5xYOwvH8/3b397XhBuucJ) with a response by Luca in regards to this problem:

```
What would happen in this circumstance?:
SELECT @rid,rid FROM MyClass
where the document contains a field called "rid".
Perhaps @rid should be return in a field called "@rid" to avoid this.
```

> This is needed because projections create field inside a temporary empty document. If it's called @rid how could you get the @rid of the temporary document (that in this case will always be -1:-1). The same is for all the document's attributes like @version, @class, @size, etc.

This seems to be a tricky problem with some undesired outcomes with either one of two possible implementations, but I think Luca's advice should be followed because of the following reasons:

1. This is a problem with the implementation of OrientDB. In my opinion a database driver should mimic the DB and original utility (in this case Console) behavior, even if it is considered incorrect.
2. It is better to have to work around an implementation limitation than get different results when using different drivers/language bindings.
3. Since this is a limitation, developers have to be aware that properties should not be named as "rid", "version", "class" or anything else that is a name reserved by the DB, with or without the **@** -- perhaps an OrientDB issue should be created with a proposal to prohibit the use of such names.
4. Again, both implementations can cause problem, but here losing data is the greater evil than having to go through the trouble of renaming a property:

```
> CREATE VERTEX V SET rid = 'I am bound to cause trouble'
Created vertex 'V#9:0{rid:I am bound to cause trouble} v1' in 0.006000 sec(s).
> SELECT @rid,rid,rid2 FROM (SELECT @rid,rid FROM #9:0)
----+------+-----+----+---------------------------
#   |@CLASS|rid  |rid2|rid22
----+------+-----+----+---------------------------
0   |null  |#-2:1|#9:0|I am bound to cause trouble
----+------+-----+----+---------------------------
```

We might not agree with how Console represents the values, but they're all there in the result set, including the temporary document RID, which is always lost when projecting using pyorient! Meanwhile, pyorient behaves in the following matter:
```
>>> DB.query("select from #9:0")[0].oRecordData
{}
>>> DB.query("select from #9:0")[0].rid
'I am bound to cause trouble'
```

Did I mess something up or did this really just happen? Also, here's another bug I just stumbled upon using the same query used in the Console example:

```
>>> DB.query("SELECT @rid,rid,rid2 FROM (SELECT @rid,rid FROM #9:3)")
Traceback (most recent call last):
...
ValueError: need more than 1 value to unpack
```

**Comment by Ostico** [comment]
Hi @sinfex ,
i changed the behaviour of OrientRecord object.

You can access directly the values of the oRecordData by calling them as OrientRecord properties.
You can access the values of the oRecordData by calling tham as dict keys.
OrientRecord now has defined _version, _rid, _class, _in, _out properties.

```python
    def test_new_projection(self):
        rec = {'@Package': {'name': 'foo', 'version': '1.0.0'}}
        x = self.client.record_create(9, rec)
        assert x._rid == '#9:0'
        assert x._version == 1
        assert x._class == 'Package'
        assert x.name == 'foo'
        assert x.version == '1.0.0'
        assert x.oRecordData['name'] == 'foo'
        assert x.oRecordData['version'] == '1.0.0'
```
