### ISSUE TITLE
DATETIME incorrectly deserialized as DATE

### ISSUE THREAD

**Issue by sinfex** [mogui/pyorient#42]
DATETIME projection is deserialized as *datetime.date* instead of *datetime.datetime*:

```
>>> DB.query("SELECT DATE('2015-01-02 03:04:05') FROM V")[0].oRecordData
{'date': datetime.date(2015, 1, 2)}
```

**Comment by jetheurer** [comment]
I am still seeing this issue: ```SELECT DATE('2015-01-02 03:04:05') FROM V``` returns ```{'DATE': datetime.datetime(2015, 1, 1, 22, 4, 5)}```

**Comment by sinfex** [comment]
@jetheurer: this seems to rather be an issue with incorrect timezone settings. Seems like either your OrientDB/JVM instance is parsing the DateTime as GMT+5, while in python you're getting a UTC representation.
