### ISSUE TITLE
Query ignore limit parameter

### ISSUE THREAD

**Issue by tomron** [mogui/pyorient#45]
`res = client.query("select from x limit 40")`
`len(res) #20`
`res = client.command("select from x limit 40")`
`len(res) #40`

**Comment by sinfex** [comment]
Funny, I was not aware this was a bug, since .query() actually supports a second (undocumented) argument for limiting the results (which, unless provided, defaults to 20):

Default limit of 20 results:
```
>>> DB.query("SELECT FROM V")
```

Limit of 200:
```
>>> DB.query("SELECT FROM V", 200)
```

Retrieving all results without limitation:
```
>>> DB.query("SELECT FROM V", -1)
```

**Comment by obi1kenobi** [comment]
https://github.com/mogui/pyorient/commit/0d551fce8e363771510613194dc74e61724c956d is an incorrect fix:

```
In [5]: len(client.query('SELECT * FROM MyTable limit 100'))
Out[5]: 21

In [6]: len(client.query('SELECT * FROM MyTable LIMIT 100'))
Out[6]: 20
```
