### ISSUE TITLE
Graph example doesn't work - yOrientCommandException: Cannot find a command executor for the command request: sql

### ISSUE THREAD

**Issue by degustator** [mogui/pyorient#46]
I tried to run example from GitHub "A GRAPH Example"

It fails at line 
    eat_edges = client.command("""
            create edge Eat
            from (select from Animal where name = 'rat')
            to (select from Food where name = 'pea')
     """)

with exception:

C:\Python27\python.exe C:/Eriks/PythonScripts/pyorient_tests.py
Traceback (most recent call last):
  File "C:/test/PythonScripts/pyorient_tests.py", line 40, in <module>
    """)
  File "C:\Python27\lib\site-packages\pyorient\orient.py", line 220, in command
    .prepare(( QUERY_CMD, ) + args).send().fetch_response()
  File "C:\Python27\lib\site-packages\pyorient\messages\commands.py", line 140, in fetch_response
    super( CommandMessage, self ).fetch_response()
  File "C:\Python27\lib\site-packages\pyorient\messages\base.py", line 143, in fetch_response
    self._decode_all()
  File "C:\Python27\lib\site-packages\pyorient\messages\base.py", line 127, in _decode_all
    self._decode_header()
  File "C:\Python27\lib\site-packages\pyorient\messages\base.py", line 115, in _decode_header
    raise PyOrientCommandException(cmd_exc, [])
pyorient.exceptions.PyOrientCommandException: Cannot find a command executor for the command request: sql.
        create edge Eat
        from (select from Animal where name = 'rat')
        to (select from Food where name = 'pea')
  - com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException

Process finished with exit code 1

**Comment by Ostico** [comment]
You're right, documentation is wrong, this is the right code:
```python
    eat_edges = client.command(
        "create edge Eat from ("
        "select from Animal where name = 'rat'"
        ") to ("
        "select from Food where name = 'pea'"
        ")"
    )
```

I updated the doc

**Comment by degustator** [comment]
Thanks. Now its working

But it seems that there is one more error. Self isn't needed in line below.

# What each animal eats?
animal_foods = client.command("select expand( out( Eat )) from Animal")
for food in animal_foods:
    animal = **self.**client.query(
                "select name from ( select expand( in('Eat') ) from Food where name = 'pea' )"
            )[0]

**Comment by Ostico** [comment]
Thanks :)
