### ISSUE TITLE
Massive Insert Intent.

### ISSUE THREAD

**Issue by tumbak** [mogui/pyorient#50]
Hello,

Is it possible to issue a massive insert intent like the Java API documented here

http://www.orientechnologies.com/docs/last/orientdb.wiki/Performance-Tuning.html#massive_insertion

thanks

**Comment by Ostico** [comment]
Hi @tumbak , but the binary protocol does not provide a method to declare intent, you can try with 
[https://github.com/mogui/pyorient#execute-orientdb-sql-batch](https://github.com/mogui/pyorient#execute-orientdb-sql-batch)

but surely this is not the same thing and could not works.
