### ISSUE TITLE
Using PyOrient in Multi-process approaches

### ISSUE THREAD

**Issue by hrugani** [mogui/pyorient#51]
Can I use the same instance of client object concurrently.
ie,
I have several objects that need persist and query data in Orientdb.
All of them work concurrently.

Can I create only one instance of Client Object and share it with all of them?

**Comment by Ostico** [comment]
Hi @hrugani ,
i've not tested concurrency, but i thik it should be safe. By the way, the socket connection is only one and all your concurrent objects will be serialized ( as for a pipeline ) because a connection pool is not implemented in the driver. So you can loose the performance advantages of the concurrency.

**Comment by hrugani** [comment]
Thank you for your feedback.

**Comment by kived** [comment]
FWIW, I had issues using pyorient in celery workers when using the default multiprocessing for concurrency, but using eventlet for concurrency did work. YMMV. With multiprocessing, if two workers tried to access the database simultaneously they would both lock up when calling select() on the orient socket, and further workers would get "resource temporarily unavailable." After switching to eventlet, I can't duplicate the issue (and indeed, when two workers run at the same time, I instead get duplicate record errors as would be expected).

**Comment by Ostico** [comment]
mmm you're telling me that the socket is a static resource? ( in such a case it would be a bug )

I imagine a pool handling some clients in this way:
```
<pseudocode>
for i in 50:
   pool += new client

pool[1].connect()
pool[2].connect()
```
and they should work indipendently and thread safe. If this is not the case the code must be fixed
