### ISSUE TITLE
OrientRecord impl creates name clash on "@<property>" vs "<property>"?

### ISSUE THREAD

**Issue by justinfx** [mogui/pyorient#52]
I'm just now checking out pyorient for the first time, and the first test I tried with the client resulted in unexpected behavior. 

My test wants to use a schema like the following:

```
{'@Package': {'name': 'foo', 'version': '1.0.0'}}
```

While this seems to be perfectly valid in OrientDB, I've discovered that the way records are implemented in pyorient creates a name clash between special `@property` names and normal `property` names. So with `@version` being a special property in OrientDB, it just becomes `aRecord.version` in pyorient, and makes it seemingly invalid to use as a user property.

Example:

```python
$ rec = {'@Package': {'name': 'foo', 'version': '1.0.0'}}
$ client.record_create(cid, rec)
PyOrientCommandException: The field 'Package.version' is mandatory, but not found on record:
Package{name:foo} - com.orientechnologies.orient.core.exception.OValidationException
```

Since `version` is being claimed by the python impl to represent the `@version`, it doesn't allow it to be a normal user property, which seems to be an unnecessary limitation. The same would be true if you had a user field called `rid`

Can this behavior be confirmed? Is it expected?

**Comment by Ostico** [comment]
Hi @justinfx 
you suggestion was already taken in consideration as suggested by @sinfex . So now i changed the behaviour of OrientRecord object.

You can access directly the values of the oRecordData by calling them as OrientRecord properties.
You can access the values of the oRecordData by calling tham as dict keys.
OrientRecord now has defined _version, _rid, _class properties.

```python
    def test_new_projection(self):
        rec = {'@Package': {'name': 'foo', 'version': '1.0.0'}}
        x = self.client.record_create(9, rec)
        assert x._rid == '#9:0'
        assert x._version == 1
        assert x._class == 'Package'
        assert x.name == 'foo'
        assert x.version == '1.0.0'
        assert x.oRecordData['name'] == 'foo'
        assert x.oRecordData['version'] == '1.0.0'
```

**Comment by justinfx** [comment]
Nice. thanks!
