### ISSUE TITLE
Index out of range at random moments

### ISSUE THREAD

**Issue by RXminuS** [mogui/pyorient#58]
I keep running into this error and after hours and hours trying to figure out how it comes about I think it's time to ask for some help. I'm starting to feel like it's something fishy in PyOrient because I can't find the origin of this problem anywhere else.

The database is properly initialised and I manage to send 100s of batch commands without a problem and then all of a sudden I send a command like this (I seen no distinguishable difference to other commands that do succeed)

``
CommandsBEGIN;let entity = SELECT FROM #12:62437;let page = CREATE VERTEX Pages CONTENT {"url": "http://www.geolink.net.au/about/accreditations/", "timestamp": "2015-04-04 20:09:26", "corpus": "Accreditations | GeoLINK                                                                              Home Featured Projects Our Services     About Us  Accreditations Company Profile Our Community   Our Team Contact us  Our Location Join Us             Accreditations           LATEST NEWS   THE GREEN PAPER \u2013 NSW Government\u2019s New Planning System      The NSW Planning Minister has recently released\u00a0The Green Paper, which sets out the government\u2019s... more \u00bb     Pacific Pines Environmental Approvals in place      This follows the State Government\u2019s approvals for the projects and will now enable a start on... more \u00bb     GeoLINK now offers Road Safety Auditing!      GeoLINK now offers Road Safety Audits in Tweed Heads, Lismore, Coffs Harbour, Newcastle and NSW... more \u00bb               \u00a0 Quality Assurance GeoLINK\u2019s policy is to provide all products and services in accordance with the client\u2019s specified requirements and best practice. The quality of our work is assured through established, purpose designed project management systems and rigorous peer review processes. GeoLINK maintains a Quality Management System meeting the requirements of AS/NZS ISO 9001 and is third party certified by BSI Australia. Certificate of Registration       \u00a0 \u00a0     \u00a0                    Project Login   Username    Password    Remember Me     Lost PasswordQUICKLINKSHome Company Profile Accreditations Our Community Contact us Join Us Our Team Past Projects LATEST NEWS   THE GREEN PAPER \u2013 NSW Government\u2019s New Planning System    Pacific Pines Environmental Approvals in place    GeoLINK now offers Road Safety Auditing!    NSW State Government Updates the Planning System    12th Annual Tree Planting Day at Lennox Head    CONTACT USLennox Head Office PO Box 119 (Level 1, 64 Ballina Street) Lennox Head, NSW 2478 Tel: +61 (0) 2 6687 7666 Coffs Harbour Office PO Box 1446 (23 Gordon Street) Coffs Harbour, NSW 2450 Tel: +61 (0) 2 6651 7666 Lismore OfficeUnit 10, Warina Walk Arcade156 Molesworth StreetLismore\u00a0 NSW\u00a0 2480      \u00a9 2015 GeoLINK Website design by Coast Studios. Find us on Facebook or Linked In"} RETURN AFTER @rid;let e = CREATE EDGE has_pages FROM $entity TO $page;COMMIT;SELECT  @rid as key from $page;  ``

and I get the following exception:

``` Traceback (most recent call last):
  File "process_items.py", line 84, in createPageVertex
    page = self.odb.batch(commands)
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/orient.py", line 246, in batch
    .prepare(( QUERY_SCRIPT, ) + args).send().fetch_response()
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/messages/commands.py", line 149, in fetch_response
    return self._read_sync()
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/messages/commands.py", line 197, in _read_sync
    res.append( self._read_record() )
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/messages/base.py", line 407, in _read_record
    _res = ORecordDecoder(__res['content'].rstrip())
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/serialization.py", line 17, in __init__
    self.__decode( content )
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/serialization.py", line 36, in __decode
    chunk = self.parse_key(content)
  File "/Users/rik/anaconda/lib/python2.7/site-packages/pyorient/serialization.py", line 104, in parse_key
    if content[ 0 ] == '"':
IndexError: string index out of range ```

Does it have anything todo with maybe a bug in the deserialisation of the Unicode corpus body?

**Comment by Ostico** [comment]
Hi @RXminuS , surely this could be a bug, i leave the issue opened and marked as bug. Next week i will investigate.

**Comment by Ostico** [comment]
Hi @RXminuS 

i tried to reproduce your issue and i tried with python 2.7.6 and python 3.4 on ubuntu system.

i used this simple script and it worked.
```python
import pyorient
import sys
import os

os.environ['DEBUG'] = "1"

DB = pyorient.OrientDB("localhost", 2424)
DB.connect("root", "root")
db_name = "test_tr"
try:
    DB.db_drop(db_name)
except pyorient.PyOrientCommandException as e:
    print(e)
finally:
    db = DB.db_create(db_name, pyorient.DB_TYPE_GRAPH,
                      pyorient.STORAGE_TYPE_MEMORY)
    pass

cluster_info = DB.db_open(
    db_name, "admin", "admin", pyorient.DB_TYPE_GRAPH, ""
)

class_id1 = DB.command( "create class Pages extends V" )[0]
class_id2 = DB.command( "create class has_pages extends E" )[0]
rec1 = { '@Pages': { 'url': 'http://www.google.com', 'timestamp': '2015-04-04 20:09:26', 'corpus': 'ok' } }
rec_position1 = DB.record_create(class_id1, rec1)

sql = 'BEGIN;let entity = SELECT FROM ' + rec_position1._rid + ';let page = CREATE VERTEX Pages CONTENT {"url": "http://www.geolink.net.au/about/accreditations/", "timestamp": "2015-04-04 20:09:26", "corpus": "Accreditations | GeoLINK Home Featured Projects Our Services About Us Accreditations Company Profile Our Community Our Team Contact us Our Location Join Us Accreditations LATEST NEWS THE GREEN PAPER \u2013 NSW Government\u2019s New Planning System The NSW Planning Minister has recently released\u00a0The Green Paper, which sets out the government\u2019s... more \u00bb Pacific Pines Environmental Approvals in place This follows the State Government\u2019s approvals for the projects and will now enable a start on... more \u00bb GeoLINK now offers Road Safety Auditing! GeoLINK now offers Road Safety Audits in Tweed Heads, Lismore, Coffs Harbour, Newcastle and NSW... more \u00bb \u00a0 Quality Assurance GeoLINK\u2019s policy is to provide all products and services in accordance with the client\u2019s specified requirements and best practice. The quality of our work is assured through established, purpose designed project management systems and rigorous peer review processes. GeoLINK maintains a Quality Management System meeting the requirements of AS/NZS ISO 9001 and is third party certified by BSI Australia. Certificate of Registration \u00a0 \u00a0 \u00a0 Project Login Username Password Remember Me Lost PasswordQUICKLINKSHome Company Profile Accreditations Our Community Contact us Join Us Our Team Past Projects LATEST NEWS THE GREEN PAPER \u2013 NSW Government\u2019s New Planning System Pacific Pines Environmental Approvals in place GeoLINK now offers Road Safety Auditing! NSW State Government Updates the Planning System 12th Annual Tree Planting Day at Lennox Head CONTACT USLennox Head Office PO Box 119 (Level 1, 64 Ballina Street) Lennox Head, NSW 2478 Tel: +61 (0) 2 6687 7666 Coffs Harbour Office PO Box 1446 (23 Gordon Street) Coffs Harbour, NSW 2450 Tel: +61 (0) 2 6651 7666 Lismore OfficeUnit 10, Warina Walk Arcade156 Molesworth StreetLismore\u00a0 NSW\u00a0 2480 \u00a9 2015 GeoLINK Website design by Coast Studios. Find us on Facebook or Linked In"} RETURN AFTER @rid;let e = CREATE EDGE has_pages FROM $entity TO $page;COMMIT;SELECT @rid as key from $page;'

record_id = DB.batch(sql)[0]

print( record_id._rid )  #  prints '#-2:0'
```

From the traceback you pasted, seems like that the response from OrientDB is corrupted and it is only space(s).

In the traceback a line is highlighted in the file "serialization.py", line [36](https://github.com/Ostico/pyorient/blob/master/pyorient/serialization.py#L36), in __decode method there is the caller line that leads to the crash:
```python
        chunk = self.parse_key(content)
```

Some lines above ( Line [25](https://github.com/Ostico/pyorient/blob/master/pyorient/serialization.py#L25) ) there is a check for a non empty string:

```python
        if not content:
            return
```
 and after that there is a:
```python
        content = content.strip()
```
to clean heading and trailing spaces. 

So, if the string was only spaces instead of something like ```'key:#11:1'```, at line [79](https://github.com/Ostico/pyorient/blob/master/pyorient/serialization.py#L79) accessing to the string index 0 inside the if statement raises an exception.
```python 
         if content[0] == '"':
``` 

Hope this helps you.

I will mark this issue as invalid. 
If you have more info/examples/tests send me them and i will try to reproduce again to help you more.
