### ISSUE TITLE
pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 29 is not supported yet by this client.

### ISSUE THREAD

**Issue by el3ctron** [mogui/pyorient#61]
i am trying to connect using your lybraries but show me this:

pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 29 is not supported yet by this client. Is the version of orientdb?

**Comment by Ostico** [comment]
What OrientDB version you are using?

**Comment by el3ctron** [comment]
Studio version : 2.0
OrientDB version : 2.1-rc1

**Comment by el3ctron** [comment]
import pyorient
client = pyorient.OrientDB("0.0.0.0", 2480)
session_id = client.connect( "admin", "admin" )




Traceback (most recent call last):
  File "/opt/mis_scripts/orientdb/crud.py", line 22, in <module>
    session_id = client.connect( "admin", "admin" )
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 207, in connect
    return self.get_message("ConnectMessage") \
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 344, in get_message
    return _Message(self._connection)\
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/connection.py", line 18, in __init__
    super( ConnectMessage, self ).__init__(_orient_socket)
  File "/usr/local/lib/python2.7/dist-packages/pyorient/messages/base.py", line 34, in __init__
    sock.get_connection()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 39, in get_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pyorient/orient.py", line 62, in connect
    " is not supported yet by this client.", [])
pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 29 is not supported yet by this client.

**Comment by Ostico** [comment]
OK, so, there is a change in the protocol version in the new release. I will add the Support in the next days.

I suggest to use, for now, a stable  OrientDB version like 2.0.8.

**Comment by el3ctron** [comment]
thanks for your quick answer!! nice software!

pd. now i am using OrientDB version : 2.0.7 and works ok.

**Comment by retrography** [comment]
But why was this closed? The issue persists on 2.1rc2

**Comment by Ostico** [comment]
Hi @retrography ,

2.1 is not a stabile release, only a release candidate. 

Pyorient Support all stable releases.

I will add the support soon.

**Comment by retrography** [comment]
Hi @Ostico,

Thanks, that would be great!

For the moment I am reverting back to 2.0.8. The issue is that I badly need the newly introduced "UNWIND" clause.

**Comment by joelschw** [comment]
Hi @Ostico, I'm in a simillar situation to @retrography. I need to use the "UNWIND" function which is part of OrientDB v2.1 rc2. Is this something that's easy to fix?

**Comment by retrography** [comment]
@joelschw, if you have serious data in your database avoid using 2.1. I found several serious bugs in it with potential for data corruption. I solved my problem with some creative data wrangling and using some simple javascript server-side functions. Hopefully 2.1 will be released soon (so many other advantages apart from UNWIND).
