### ISSUE TITLE
Ref: db.command hanging with 100% CPU #2

### ISSUE THREAD

**Issue by Ostico** [mogui/pyorient#68]
Ref:
[db.command hanging with 100% CPU #2](https://github.com/orientechnologies/pyorient/issues/2)

**Comment by dyroffk** [comment]
I'm also able to reproduce this problem of PyOrient hanging on successive commands.  Is there anything we can provide to help diagnose/resolve?

**Comment by Ostico** [comment]
I will work on this ad soon ad possible. This week i think.

**Comment by Ostico** [comment]
@omgold , @dyroffk 

I fixed the issue, by the way, there are a syntax error in the statement
```
"create index KEY on obj _KEY unique"
```

it should be:
```
"create index KEY on obj ( _KEY ) unique"
```
