### ISSUE TITLE
Problems after issuing an alter command

### ISSUE THREAD

**Issue by neRok-** [mogui/pyorient#70]
I frequently create a new in memory database for my development. The workflow was create database, create classes and properties, then import my data. I have decided to use lightweight edges, so I need to introduce the command `client.command('alter database custom useLightweightEdges=true')` into my workflow. Whenever I issue the alter command, it successfully alters the database, but it causes issues between pyorient and the database.

If I create the database, issue the alter command, then attempt to create a class, I get the following (abbreviated) error. If I look at the database with the OrientDB Studio web-app, the class is created.
>   File "pyorient\orient.py", line 242, in command
>     .prepare(( QUERY_CMD, ) + args).send().fetch_response()
>   File "pyorient\messages\commands.py", line 149, in fetch_response
>     return self._read_sync()
>   File "pyorient\messages\commands.py", line 179, in _read_sync
>     response_type = response_type.decode()
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 0: invalid
> start byte

If I create the database, create the classes, issue the alter command and then try to create a record, I get the following (abbreviated) error. If I look at the database with the OrientDB Studio web-app, the record is created.
>   File "pyorient\orient.py", line 286, in record_create
>     .prepare(args).send().fetch_response()
>   File "pyorient\messages\records.py", line 124, in fetch_response
>     self._decode_field( FIELD_LONG ),  # (uuid-most-sig-bits:long)
>   File "pyorient\messages\base.py", line 290, in _decode_field
>     _value = self._orientSocket.read( _type['bytes'] )
>   File "pyorient\orient.py", line 105, in read
>     n_bytes = self._socket.recv_into(view, _len_to_read)
> socket.timeout: timed out

If I create a database with the webapp and set it to use lightweight edges, then create my classes and records via pyorient, everything works fine.

Hopefully I have provided enough info to locate the problem, and that it is in fact a problem and not something I have done wrong. If it matters, I am on win7-x64 and using OrientDB 2.0.2 and pyorient 1.4.

**Comment by Ostico** [comment]
This issue is fixed since commit db3d0b243a18b23050fd35a4c69a93bc0e6d79ae

Close.
