### ISSUE TITLE
PyOrientCommandException construction

### ISSUE THREAD

**Issue by sinfex** [mogui/pyorient#73]
[PyOrientCommandException](/mogui/pyorient/blob/master/pyorient/messages/base.py#L179-180) in base.py does not hold the exception class/message separately. It is also constructed using bytes and converted to an ugly representation when [PyOrientException's \__str()\__](/mogui/pyorient/blob/master/pyorient/exceptions.py#L9-13) is called in exceptions.py:

> pyorient.exceptions.PyOrientCommandException: **b"**Database 'plocal:/opt/orientdb/databases/testdb' is closed - com.orientechnologies.orient.core.exception.ODatabaseException"

This makes cases like #72 even more cumbersome. May I suggest you replace

> cmd_exc = exception_message + b' - ' + exception_class
> raise PyOrientCommandException(cmd_exc, [])

with

> raise PyOrientCommandException(exception_class.decode('utf8'), [exception_message.decode('utf8')])

?

**Comment by Ostico** [comment]
Tnx @sinfex ,

really a good idea.
