### ISSUE TITLE
Invalid handling of OrientRecordLink lists inside pyorient/serialization.py(498)parse_value()

### ISSUE THREAD

**Issue by mcaramma** [mogui/pyorient#77]
The following code do not handle correctly list of links

                    map(lambda elem: self.parse_value(type(value[0])(elem)),
                            value)) + ']'

For OrientRecordLink objects `type(value[0])(elem)` raise `[AttributeException: OrientRecordLink has not attribute 'split']`.

One possible way to fix it is adding an isinstance() check like this:

                     map(lambda elem: self.parse_value(type(value[0])(elem))\
                                      if not isinstance(value[0], OrientRecordLink)\
                                      else elem.get_hash(),
                            value)) + ']'

Thanks

**Comment by Ostico** [comment]
Hi @mcaramma ,

can you provide a simple code example to reproduce the issue?

Tnx in advance.

**Comment by Ostico** [comment]
Hi @mcaramma ,

no more needed i found the issue, your code is right, i created a test also.
