### ISSUE TITLE
get cluster from class name

### ISSUE THREAD

**Issue by Hrabal** [mogui/pyorient#78]
Hi,

I'm trying to implement a "create class if not exists" function in this form:

try:
    cluster_id = client.command("create class {0} extends V".format(class_name))
except:
    cluster_id = ????

I can't find a way to get the supported cluster list of a class, tried client.command("info class {0}".format(class_name)) and return this exception:

pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException - Cannot find a command executor for the command request: sql.info class

is there a way to retrive the cluster list having a class name?

p.s: also, commands "classes" and "browse class xyz" returns the same error..

**Comment by Ostico** [comment]
Hi @Hrabal ,

sure you can.

With db_open message you obtain an Information object
```python
assert isinstance( client.db_open( "GratefulDeadConcerts", "admin", "admin" ), pyorient.Information )
```
or you can use the ```db_reload``` command to obtain the same info.

Take a look to this:
https://github.com/mogui/pyorient/blob/master/pyorient/messages/cluster.py#L243

You can access to the ID by the name
```python
Information.get_class_position( 'className' )
```
or to the name from it's ID
```python
Information.get_class_name( 11 )
```

**Comment by Hrabal** [comment]
Thanks @Ostico 
The Information object seems gold!

I'll search in the code for some other goodies regarding db classes handling.

btw: I've made a "opening object" based on the OrientDb class, so I can use "with OpenDb() as db: du stuff"... There is already an object in pyorient with methods __enter__ and __exit__?
I'm sure if there is I't better of mine :)

Grazie

**Comment by Ostico** [comment]
Hi @Hrabal , not at the moment, if you implemented some kind of useful stuffs, send me a pull request with some test also, i will try them and hopefully i will merge :smile:

**Comment by mogui** [comment]
#101 should make this more easy :)
and I'm opening this #102 cause the opening object it's interesting
