### ISSUE TITLE
is it possible to create an edge using record_create()?

### ISSUE THREAD

**Issue by lebedov** [mogui/pyorient#85]
Is it possible to create an edge between existing vertices using `record_create()` rather than passing an explicit create SQL query to the `command()` method? If so, how should one specify the vertex information? Passing a record like `{@E: {'in': '#9:123', 'out': '9:124'}}` to `record_create()` creates an edge, but doesn't appear to connect the vertices. (I saw https://github.com/mogui/pyorient/issues/12, but it doesn't appear provide a clear answer.) I'm using the latest revision of pyorient with OrientDB 2.0.12.

**Comment by Ostico** [comment]
Hi @lebedov ,

sorry, from what I know is not possible to create edges between vertex with CRUD commands.
You must use SQL ( the link you provided https://github.com/mogui/pyorient/issues/12 is a good example ) or the batch command ( https://github.com/mogui/pyorient/blob/master/test/test_reserved_words_batch.py#L154 )
