### ISSUE TITLE
nosetests failed with correct user password

### ISSUE THREAD

**Issue by gg4u** [mogui/pyorient#95]
Tried to run a test, I updated test.cfg :

[server]
host: localhost
port: 2424
canroot: 0
[root]
user: user
pwd: pwd
[user]
user: user
pwd: pwd
[db]
existing: GratefulDeadConcerts
new: new_test_db

but a nosetests will keeps on finding 59 errors due to configuration:
'Get the user/password from the config/orientdb-server-config.xml file'
*Is there any other configuration to be done?*

** update **
first error found is in line 22 of test_record_contents.py
where:
self.client.connect( "root", "root" )

so in setUp(self) function it looks there are hardcoded pwd and username.
Tried to changed my ones in 
config/orientdb-server-config.xml
file to meet 'root root' and 'admin admin', no change: 59 failed tests.

I also see there are two test.cfg files:
one in root folder and another one in test folder.

Please indicate how to proceed for proper configuration.

**Comment by mogui** [comment]
Hi @gg4u, 
that config file is no longer used to run tests the correct way this is the procedure:

- ensure you have **ant** installed
- run `./ci/start-ci.sh`    
*this will download latest version of orient, mangle with few configuration and database and then run orient in background note that if you want to shutdown orient you've to find and kill the process manually*
- then you can finally run `nosetests`

I will shortly point this in the README
