### ISSUE TITLE
massive insertion: no transacations?

### ISSUE THREAD

**Issue by gg4u** [mogui/pyorient#96]
Hi, 
I will need to insert the graph on batch.
I woudl break the process in two steps: inserting blocks of vertex first, then block of edges.

I was thinking to use transactions, but read the recommendation of Luca:
https://groups.google.com/d/msg/orient-database/wYT5lAlRXow/ULVNvgFTLB0J
don't use transactions (2012).
The link he pointed out has been also moved: 
http://orientdb.com/docs/last/orientdb.wiki/Performance-Tuning.html
( see: https://groups.google.com/forum/#!topic/orient-database/wYT5lAlRXow )

Could you please appoint how to make a batch insertion in python / pyorient?

I tried to import a graph.ml object from neo4j but keeps on failing, and I m trying again from scratch (also because I will have, too), but so far struggling in getting the db uploaded.

Better ask on stackoverflow or is it ok here, since official driver ?
thank you!

**Comment by Ostico** [comment]
Hi @gg4u ,

in the bynary protocol ( and in pyorient of course ) there is not the massive insert intent.

Please refer to:
https://github.com/mogui/pyorient/issues/50

**Comment by lebedov** [comment]
@gg4u: Although it's probably faster to use OrientDB's ETL mechanism if it isn't too hard to convert your graphml file into CSV or JSON, splitting your list of vertex/edge insertions into batches via the existing [batch mechanism](https://github.com/mogui/pyorient#execute-orientdb-sql-batch) might be acceptable; I've used this approach to load graphs of about 10000 vertices and 30000 edges in a few minutes.

**Comment by gg4u** [comment]
Yes I will do that in the end, - I would have like to try a parallel import since graph is 1000 times larger and previous attempt in importing an exported graph.ml of 16gb failed.
